# checking array properties

In [1]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr.shape

(3,)

In [4]:
import numpy as np
arr = np.array([[10, 20, 30],[40,50,60]])

In [5]:
arr.shape

(2, 3)

In [6]:
arr.size

6

In [7]:
arr.ndim

2

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr=np.array([1.1,2.2,3.3],dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [10]:
import numpy as np

arr = np.array([1.1, 2.2, 3.3], dtype=np.int64)
print(arr)

[1 2 3]


In [11]:
arr=np.array([1.1,2.2,3.3])
arr1=arr.astype(np.int64)
arr1

array([1, 2, 3])

In [12]:
arr=np.array([[1,2,3],[2,5,3],[4,2,4],[5,6,7]])
arr

array([[1, 2, 3],
       [2, 5, 3],
       [4, 2, 4],
       [5, 6, 7]])

In [13]:
arr.shape

(4, 3)

In [14]:
arr.size

12

In [15]:
my_arr=arr.reshape(3,4)

In [16]:
my_arr

array([[1, 2, 3, 2],
       [5, 3, 4, 2],
       [4, 5, 6, 7]])

In [17]:
arr.reshape(6,2)

array([[1, 2],
       [3, 2],
       [5, 3],
       [4, 2],
       [4, 5],
       [6, 7]])

In [18]:
arr.reshape(1,12)

array([[1, 2, 3, 2, 5, 3, 4, 2, 4, 5, 6, 7]])

In [19]:
arr.reshape(2,6)

array([[1, 2, 3, 2, 5, 3],
       [4, 2, 4, 5, 6, 7]])

In [20]:
my_arr=arr.flatten() #convert multi dimention array into single dimention

In [21]:
my_arr

array([1, 2, 3, 2, 5, 3, 4, 2, 4, 5, 6, 7])

# indexing and slicing

In [23]:
arr=np.array([50,60,70,80,90,55])

In [24]:
print(arr[0])

50


In [25]:
print(arr[-1])

55


In [26]:
arr[0:5]

array([50, 60, 70, 80, 90])

In [27]:
arr[0:6]

array([50, 60, 70, 80, 90, 55])

In [28]:
arr[:4] #equal to arr[0:4]

array([50, 60, 70, 80])

In [29]:
arr[2:] #equal to [2:6]

array([70, 80, 90, 55])

In [30]:
my_list=[1,2,3,4,5,6]
print(my_list)
new_list=my_list[0:4]
print(new_list)
new_list[0]=100
print(new_list)
print(my_list)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4]
[100, 2, 3, 4]
[1, 2, 3, 4, 5, 6]


In [31]:
my_array=np.array([1,2,3,4,5,6])
print(my_array)
new_array=my_array[0:4]
print(new_array)
new_array[0]=100
print(new_array)
print(my_array)

[1 2 3 4 5 6]
[1 2 3 4]
[100   2   3   4]
[100   2   3   4   5   6]
