# creation of numpy array

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a1=np.array([1,2,34,4])
print(a1)
print(*a1)
print(a1.ndim)

[ 1  2 34  4]
1 2 34 4
1


In [3]:
a2=np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [4]:
a3=np.array([["a","b","c"],[1,2,3],[4,5,6]])
print(a3)
print(*a3)
print(a3.ndim)

[['a' 'b' 'c']
 ['1' '2' '3']
 ['4' '5' '6']]
['a' 'b' 'c'] ['1' '2' '3'] ['4' '5' '6']
2


In [5]:
a4=np.array([34])
print(a4)
print(*a4)
print(a4.ndim)

[34]
34
1


# built-in methods

In [44]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [50]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

# multidimentional array mathematical operations

In [6]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arr1.shape

(4, 3)

In [8]:
arr1[0][1]

np.int64(2)

In [9]:
arr1[2,1]

np.int64(8)

In [10]:
arr1[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [11]:
arr1[1:4,1:3]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

# 3D array indexing and slicing

In [12]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [13]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
arr[0,1,2]

np.int64(6)

In [15]:
arr[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

# built in mathematical functions

In [18]:
arr=np.array([1,2,3,4,5])

In [19]:
np.mean(arr)

np.float64(3.0)

In [20]:
np.max(arr)

np.int64(5)

In [23]:
np.min(arr)

np.int64(1)

In [24]:
np.std(arr)

np.float64(1.4142135623730951)

In [25]:
np.var(arr)

np.float64(2.0)

In [26]:
np.sum(arr)

np.int64(15)

In [27]:
np.prod(arr)

np.int64(120)

In [28]:
np.median(arr)

np.float64(3.0)

In [31]:
np.percentile(arr,50)

np.float64(3.0)

In [32]:
np.argmin(arr)

np.int64(0)

In [33]:
np.argmax(arr)

np.int64(4)

In [34]:
np.corrcoef(arr)

np.float64(1.0)

In [35]:
x=[1,2,3,4]
y=[2,4,6,8]
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [36]:
x=[1,2,3,4]
y=[8,6,4,2]
np.corrcoef(x,y)

array([[ 1., -1.],
       [-1.,  1.]])

In [37]:
x=[1,2,3,4]
y=[6,2,4,7]
np.corrcoef(x,y)

array([[1.        , 0.29111125],
       [0.29111125, 1.        ]])

In [38]:
arr1=np.array([1,2,3,4,5,2,4,6,4,2])
np.unique(arr1)

array([1, 2, 3, 4, 5, 6])

In [39]:
arr1=np.array([1,2,3,4,5])
np.diff(arr)

array([1, 1, 1, 1])

In [40]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

In [41]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [42]:
np.log(1)

np.float64(0.0)

In [43]:
np.exp(1)

np.float64(2.718281828459045)

# declaration of array (data types in numpy)

In [51]:
a5=np.array([1,2,3],dtype='i4')
a5

array([1, 2, 3], dtype=int32)

In [52]:
a5=np.array([1,2,3],dtype='int32')
a5

array([1, 2, 3], dtype=int32)

In [53]:
a5=np.array([1,2,3],dtype='S')
a5

array([b'1', b'2', b'3'], dtype='|S1')

In [54]:
a5=np.array([1,'2',3.5])
a5

array(['1', '2', '3.5'], dtype='<U32')

In [55]:
a5=np.array([1,'2','3.5'],dtype='<U32')
a5

array(['1', '2', '3.5'], dtype='<U32')

In [56]:
import numpy as np

a = np.array([True, False, True], dtype='bool')
print(a)
print(a.dtype)

[ True False  True]
bool


In [57]:
b=np.array(['apple','banana','pineapple'])
print(b)
print(b.dtype)

['apple' 'banana' 'pineapple']
<U9


In [58]:
# Changing Data Type
c=np.array([1.2,2.2,3.2])
print(c)
d=c.astype(int)
print(d)
print(d.dtype)

[1.2 2.2 3.2]
[1 2 3]
int64


# practice

In [59]:
# Create a NumPy array from the list [1,2,3,4,5].
import numpy as np
a1=np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [60]:
#Create a 1D array of numbers from 0 to 9
import numpy as np

arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
#Create a 3×3 array filled with zeros.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
#Create a 4×4 array filled with ones.
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
#Create a 3×3 array filled with the number 7.
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])