# numpy array

# practice

In [2]:
# Given a Numpy array, write a function to compute the sum of all its elements.
import numpy as np

arr=np.array([1,2,3,4,5])
total=np.sum(arr)
print(total)

15


In [4]:
# Given a Numpy array, write a function to find the maximum element in the array.
arr=np.array([1,2,7,9,5])
df=np.max(arr)
df


np.int64(9)

In [6]:
# Given a Numpy array, write a function to compute the mean (average) of the elements in the array.
arr=np.array([2,4,6,8,10])
df=np.mean(arr)
df


np.float64(6.0)

In [11]:
# Given a Numpy array, write a function to reshape the array into a 2D array with a specified number of rows and columns.
arr=np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [12]:
arr=np.array([1,2,3,4,5,6])
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
#Given a Numpy array, write a function to compute the standard deviation of the elements  the array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
df=np.std(arr)
print(df)

1.4142135623730951


In [22]:
np.std(arr)

np.float64(1.4142135623730951)

In [23]:
# Given a Numpy array, write a function to perform element-wise exponentiation (raise each element to a power).
array = np.array([1, 2, 3, 4])
exponent = 2
expo=array**2
print(expo)

[ 1  4  9 16]


In [33]:
# Given two Numpy arrays, write a function to concatenate them along a given axis.
array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

axis = 0

result=np.concatenate((array1,array2),axis=0)
print(result)

[1 2 3 4 5 6]


In [35]:
# Given a 2D Numpy array, write a function to reverse the rows of the array.
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reverse=array[::-1]
print(reverse)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [43]:
# Given a 2D Numpy array, write a function to extract the diagonal elements.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal=np.diag(arr)
print(diagonal)

[1 5 9]


In [58]:
# Given a list of lists, write a function to create a 3D Numpy array.
data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
df=np.array(data)
df

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [61]:
# Given a 3D Numpy array, write a function to access an element at a given index (x, y, z).
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
index=(1,0,1)

print(array[1,0,1])

6


In [77]:
# Given a 3D Numpy array, write a function to find the maximum element along each axis.
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
result=np.max(array,axis=0)
print(result)
result=np.max(array,axis=1)
print(result)
result=np.max(array,axis=2)
print(result)


[[ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [10 11 12]]
[[ 3  6]
 [ 9 12]]


In [86]:
# Given a 3D Numpy array, write a function to flatten it into a 1D array.
import numpy as np

array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result = array.flatten()

print(result)

[1 2 3 4 5 6 7 8]


# numpy matrix

# 1.Maximum value from given matrix

In [69]:
# create 2x2 matrix and find the max
import numpy as np
m=np.matrix('[23,12;34,56]')
mx=m.max()
print(mx)

56


# 2.Minimum value from given matrix

In [6]:
# finding min()
m=np.matrix('[23,12;34,56]')
mx=m.min()
print(mx)

12


# 3.Find number of rows and columns of a given matrix

In [70]:
# finding no of rows and column
#using shape()
n=np.matrix([[23,45,61],[1,23,41]])
rows,columns=n.shape
print("Rows:",rows)
print("Column:",columns)

Rows: 2
Column: 3


In [10]:
#using indexing[]
n=np.matrix([[23,45,61],[1,23,41]])
rows=n.shape[0]  # 0 gives number of rows
columns=n.shape[1] # 1 gives number of columns
print("Rows:",rows)
print("Column:",columns)

Rows: 2
Column: 3


In [19]:
#using reshape()
import numpy as np
m=np.arange(0,12).reshape((4,3))
print(m)
rows,columns=m.shape
print("Rows:",rows)
print("Column:",columns)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Rows: 4
Column: 3


#### 

In [45]:
#selecting perticular value in matrix
#using matrix.take(index, axis)
import numpy as np
std=np.matrix('[12,13,14;17,15,16;18,19,20]')
arr=std.take(1, 1)
print(arr)

[[13 15 19]]


In [56]:
import numpy as np
std=np.matrix('[1,2,3,4,5,6]')
arr=std.take(2, 1)
print(arr)

[[3]]


# 4.Select elements from a given matrix

In [57]:
# finding sum of matrix
# using matrix.sum()
import numpy as np
std=np.matrix('[12,13,14;17,15,16;18,19,20]')
print(std)

[[12 13 14]
 [17 15 16]
 [18 19 20]]


In [58]:
add=std.sum()
print(add)

144


# 5.Find sum of values in a matrix

In [59]:
a=np.matrix([[1,2],[3,4]])
print(a)
add=a.sum()
print(add)

[[1 2]
 [3 4]]
10


In [66]:
# adding each row
add=a.sum(axis=1) 
print(add)

[[3]
 [7]]


In [67]:
#adding each column
add=a.sum(axis=0) 
print(add)

[[4 6]]


# 6.Calculate sum of the diagonal elements

In [77]:
# numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)  
#numpy.trace()
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print("Numpy matrix is:")
print(arr1)

a=np.trace(arr1)

print("\nTrace of given 3X3 matrix:")
print(a)

Numpy matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace of given 3X3 matrix:
15


In [78]:
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
a=np.trace(arr1)
print(a)

15


In [76]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the Trace of a matrix
trace = np.trace(n_array)


print("\nTrace of given 3X3 matrix:")
print(trace)

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


# 7.Adding and Subtracting Matrices

In [82]:
a=np.matrix('[1,2,3]')
b=np.matrix('[4,5,6]')

print("Matrix a is :\n",a)
print("Matrix b is :\n",b)

c=np.add(a,b)
print("Result :\n",c)


Matrix a is :
 [[1 2 3]]
Matrix b is :
 [[4 5 6]]
Result :
 [[5 7 9]]


In [86]:
import numpy as np
a=np.matrix('[10,20,30]')
b=np.matrix('[4,5,6]')

print("Matrix a is :\n",a)
print("Matrix b is :\n",b)

d=np.subtract(a,b)
print("Result :\n",d)

Matrix a is :
 [[10 20 30]]
Matrix b is :
 [[4 5 6]]
Result :
 [[ 6 15 24]]


# 8.Ways to add row/columns

In [92]:
#np.append
a=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11],[12],[13]])  
c=np.append(a,b,axis=1)
print(c)

[[ 1  2  3 11]
 [ 4  5  6 12]
 [ 7  8  9 13]]


In [95]:
#np.insert
a=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([11,12,13])
n = a.shape[0]  
c=np.insert(a,n,b,axis=0)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


# 9.Matrix Multiplication

In [98]:
import numpy as np
a = [[1, 2], [2, 3]]
b = [[4, 5], [6, 7]]

print("Matrix a is :\n",a)
print("Matrix b is :\n",b)

c=np.dot(a,b)
print("Result :\n",c)

Matrix a is :
 [[1, 2], [2, 3]]
Matrix b is :
 [[4, 5], [6, 7]]
Result :
 [[16 19]
 [26 31]]


# 10.Get eigen values of a matrix

In [99]:
from numpy import linalg as LA
val = LA.eigvals([[1, 2], [3, 4]])
print(val)

[-0.37228132  5.37228132]


In [100]:
from numpy import linalg as LA
a=LA.eigvals([[1,2,3],[4,5,6],[6,7,8]])
print(a)

[ 1.50000000e+01 -1.00000000e+00  1.08312207e-16]
